# Generated by Django 3.2.3 on 2022-05-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('age', models.IntegerField(max_length=1)),
                ('gender', models.BooleanField()),
            ],
            options={
                'db_table': 'client_data',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('number', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'shop_info',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('price', models.IntegerField(max_length=6)),
                ('client_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.client')),
            ],
            options={
                'db_table': 'product_card',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=2)),
                ('sizes', models.IntegerField(max_length=40)),
                ('image', models.CharField(max_length=300)),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.product')),
            ],
            options={
                'db_table': 'product_color',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='shop_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.shop'),
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=26)),
                ('text', models.CharField(max_length=78)),
                ('image', models.CharField(max_length=300)),
                ('shop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.shop')),
            ],
            options={
                'db_table': 'advertising',
            },
        ),
    ]
