# Generated by Django 3.2.3 on 2022-05-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='shop_info',
        ),
        migrations.AddField(
            model_name='color',
            name='article',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(max_length=300, upload_to='media/advertising'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='shop_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Взрослый'), (2, 'Тинейджер'), (3, 'Ребенок')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(max_length=300, upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='color',
            name='product_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product'),
        ),
        migrations.AlterField(
            model_name='color',
            name='sizes',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=300, upload_to='media/shops'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.CharField(max_length=11),
        ),
    ]
