# Generated by Django 3.2.3 on 2022-05-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0003_auto_20220512_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')])),
                ('gender', models.IntegerField(choices=[(1, 'Взрослый'), (2, 'Тинейджер'), (3, 'Ребенок')])),
            ],
            options={
                'db_table': 'client_data',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(max_length=300, upload_to='media/shops')),
            ],
            options={
                'db_table': 'shop_info',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('price', models.CharField(max_length=6)),
                ('client_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.client')),
                ('shop_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop')),
            ],
            options={
                'db_table': 'product_card',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=2)),
                ('article', models.CharField(default='', max_length=12)),
                ('sizes', models.CharField(max_length=40)),
                ('image', models.ImageField(max_length=300, upload_to='media/products')),
                ('product_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product')),
            ],
            options={
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=26)),
                ('text', models.CharField(max_length=78)),
                ('image', models.ImageField(max_length=300, upload_to='media/advertising')),
                ('shop_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop')),
            ],
            options={
                'db_table': 'advertising',
            },
        ),
    ]
