# Generated by Django 3.2.3 on 2022-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_advertising_client_color_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(max_length=300, upload_to='advertising'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(max_length=300, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=300, upload_to='shops'),
        ),
    ]
