# Generated by Django 3.2.3 on 2022-05-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220512_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client_data',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='login',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='password',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Взрослый'), (2, 'Тинейджер'), (3, 'Ребенок')], null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='comp_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
