# Generated by Django 3.2.3 on 2022-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220513_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='auth_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
