# Generated by Django 3.2.3 on 2022-05-13 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_shop_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(max_length=300, upload_to='advertising', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='shop_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='text',
            field=models.CharField(max_length=78, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title',
            field=models.CharField(max_length=26, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='color',
            name='article',
            field=models.CharField(default='', max_length=12, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=2, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(max_length=300, upload_to='products', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='color',
            name='product_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='color',
            name='sizes',
            field=models.CharField(help_text='Используйте формат: 41 42 43 ..', max_length=40, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')], null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Взрослый'), (2, 'Тинейджер'), (3, 'Ребенок')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='auth_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comp_name',
            field=models.CharField(default='', max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=300, upload_to='shops', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
