# Generated by Django 3.2.3 on 2022-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20220513_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title',
            field=models.CharField(max_length=59, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.IntegerField(choices=[(1, 'Черный'), (2, 'Зеленый'), (3, 'Синий'), (4, 'Синий'), (5, 'Синий')], verbose_name='Цвет'),
        ),
    ]
