# Generated by Django 3.2.3 on 2022-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20220513_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.IntegerField(choices=[(1, 'Черный'), (2, 'Зеленый'), (3, 'Синий'), (4, 'Красный'), (5, 'Белый')], verbose_name='Цвет'),
        ),
    ]
