# Generated by Django 3.2.3 on 2022-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20220513_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Corneliani', 'Corneliani')], max_length=40, null=True, verbose_name='Бренд'),
        ),
    ]
