# Generated by Django 3.2.3 on 2022-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name': 'рекламу', 'verbose_name_plural': 'Рекламные баннеры'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'цвет товара', 'verbose_name_plural': 'Цвета для карточек товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Карточки товаров'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=120, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Corneliani', 'Corneliani'), ('Puma', 'Puma')], max_length=40, null=True, verbose_name='Бренд'),
        ),
    ]
