# Generated by Django 3.2.3 on 2022-05-14 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20220514_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='sizes',
            field=models.CharField(help_text='Используйте формат: 41 42 43 ..', max_length=40, validators=[django.core.validators.RegexValidator(message='Размеры указаны неверно, смотрите подсказки', regex='(\\d{2} )*(\\d{2})')], verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(choices=[(1, 'Взрослый'), (2, 'Тинейджер'), (3, 'Ребенок')], default=1, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Женщина'), (2, 'Мужчина')], default=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text='Введите число до: 999999', max_length=6, validators=[django.core.validators.RegexValidator(message='Цена указана неверно, смотрите подсказки', regex='\\d')], verbose_name='Цена'),
        ),
    ]
