# Generated by Django 3.2.3 on 2022-05-14 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20220514_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='sizes',
            field=models.CharField(help_text='Используйте формат: 41 42 43 ..', max_length=40, validators=[django.core.validators.RegexValidator(message='Размеры указаны неверно, смотрите подсказки', regex='^(\\d{2} )*(\\d{2})$')], verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text='Введите число до: 999999', max_length=6, validators=[django.core.validators.RegexValidator(message='Цена указана неверно, смотрите подсказки', regex='^[0-9]+$')], verbose_name='Цена'),
        ),
    ]
