# Generated by Django 3.2.3 on 2022-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20220516_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='Выберите материал', max_length=120, verbose_name='Материал'),
        ),
    ]
