# Generated by Django 3.2.3 on 2022-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(max_length=300, unique=True, upload_to='advertising', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.ImageField(max_length=300, unique=True, upload_to='products', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='auth_user_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(max_length=300, unique=True, upload_to='shops', verbose_name='Фон'),
        ),
    ]
