# Generated by Django 3.2.3 on 2022-05-17 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20220517_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='shop_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='color',
            name='product_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shop', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='auth_user_id',
            field=models.IntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Владелец'),
        ),
    ]
