# Generated by Django 3.2.3 on 2022-05-18 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0023_auto_20220517_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='auth_user_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='auth_user',
            field=models.ForeignKey(default=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='shop_info',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='index.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='color',
            name='product_card',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='index.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_info',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='index.shop', verbose_name='Магазин'),
        ),
    ]
