# Generated by Django 3.2.3 on 2022-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20220518_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Corneliani', 'Corneliani'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Prada', 'Prada')], default=False, max_length=40, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default=False, max_length=320, verbose_name='Описание'),
        ),
    ]
