# Generated by Django 3.2.3 on 2022-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20220519_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=False, max_length=320, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.IntegerField(choices=[(1, 'Лето'), (2, 'Зима'), (2, 'Демисезон')], default=False, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='Выберите материал', max_length=120, verbose_name='Материал'),
        ),
    ]
