# Generated by Django 3.2.3 on 2022-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_auto_20220519_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='text',
            field=models.TextField(max_length=120, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Corneliani', 'Corneliani'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Prada', 'Prada'), ('Balenciaga', 'Balenciaga'), ('Gucci', 'Gucci'), ('Off-White', 'Off-White'), ('Saint Laurent', 'Saint Laurent'), ('Tom Ford', 'Tom Ford'), ('Valentino', 'Valentino'), ('Louis Vuitton', 'Louis Vuitton')], default=False, max_length=40, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Добавьте описание', max_length=320, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.IntegerField(choices=[('Обувь', ((101, 'Ботинки'), (102, 'Кроссовки и кеды'), (103, 'Сандалии'), (104, 'Туфли'))), ('Одежда', ((201, 'Верхняя одежда'), (202, 'Брюки'), (203, 'Футболки'), (204, 'Рубашки'), (205, 'Трикотаж'), (206, 'Юбки'))), ('Аксессуары', ((301, 'Галстуки'), (302, 'Зонты'), (303, 'Часы'), (304, 'Ремни и пояса'), (305, 'Сумки')))], default=False, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(default='', max_length=300, verbose_name='Описание'),
        ),
    ]
