# Generated by Django 3.2.3 on 2022-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_auto_20220519_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='yandex_rates_id',
            field=models.IntegerField(default=None, verbose_name='Индекс яндекс отзывов'),
        ),
    ]
