# Generated by Django 3.2.3 on 2022-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_shop_yandex_rates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='yandex_rates_id',
            field=models.BigIntegerField(default=None, help_text='Найдите свою организацию на Яндекс Картах, откройте список отзывов, затем скопируйте цифровой код после названия вашей организации из URL', verbose_name='Индекс яндекс отзывов'),
        ),
    ]
